version: '3.8'

services:
  db:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: desafio_redizz
      MYSQL_USER: redizz_user
      MYSQL_PASSWORD: redizz_user
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./schema-utilizado-desafio.sql:/docker-entrypoint-initdb.d/schema-utilizado-desafio.sql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: redizz_user
      DB_PASSWORD: redizz_user
      DB_SCHEMA: desafio_redizz
      JWT_SECRET: desenvolvedor-contratado
      JWT_EXPIRES: 15d
    depends_on:
      - db
